version: '3.7'

volumes:
  dados:

networks:
  localdev:    
    
services:

  postgres:    
    image: postgres:10.0
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - localdev
    container_name: db-postgres
    environment:      
      POSTGRES_PASSWORD: "global2019"      
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - localdev    
    ports:
      - "5000:80"
    environment:
      - DBHOST=postgres
    depends_on:
      - postgres