version: '3.7'

services:
  webapi:
    image: testeapi
    ports:
      - "8000:80"
    depends_on:
      - db-postgres
    networks:
      - postgres-compose-network

  db-postgres:
    image: postgres:latest
    container_name: db-postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-WebApiBlog}  
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes: 
      - "./pgadmin:/root/.pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    ports:
      - "${PGADMIN_PORT:-15432}:80"
    depends_on:
      - db-postgres
    networks:
      - postgres-compose-network   

volumes:
  db_volume:
 
networks: 
  postgres-compose-network: