version: '3.7'

networks: 
  postgres-compose-network:
    driver: bridge

services:
  webapi:
    image: ${DOCKER_REGISTRY-}testeapi
    build: 
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:80"
    networks:
      - postgres-compose-network

  db-postgres:
    image: postgres:latest
    container_name: db-postgres
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-WebApiBlog}  
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes: 
      - "./pgadmin:/root/.pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    ports:
      - "${PGADMIN_PORT:-15432}:80"
    depends_on:
      - db-postgres
    networks:
      - postgres-compose-network      

volumes:
  db_volume: